### ISSUE TITLE
may I suggest

### ISSUE THREAD

**Issue by fredzannarbor** [Shubhamsaboo/kairos_gpt3#3]
renaming the directories "GPT-3 Sandbox" and "Programming with GPT-3" to replace the spaces with underscores?  The first thing I did on cloning was to rename them accordingly.  I am hoping this doesn't bite me in the future.  Having directories with spaces in the names seems like it's bound to create problems.

**Comment by Shubhamsaboo** [comment]
Hey Fred!

That's a great suggestion. Incorporated the feedback 🙏 

Thanks,
Shubham
