### ISSUE TITLE
how do I specify how long I want the reply to be?

### ISSUE THREAD

**Issue by dfrankle2** [Shubhamsaboo/kairos_gpt3#5]
thanks!

**Comment by Shubhamsaboo** [comment]
You can change the value of "max token" in the [model_training_service.py file](https://github.com/Shubhamsaboo/kairos_gpt3/blob/master/GPT-3_Sandbox/email_generation/model_training_service.py) depending on the length of response you want. Think of tokens as words and set the token length appropriately. 

Hope that answers your question!

**Comment by dfrankle2** [comment]
Hi Shubhamsaboo, how would I change the model training service program to ignore the training data if I want to juse use the finetuned model? 

I have been finetuning curie to a few use cases. Let me know. 
Thanks so much for all your help and for making this public!

**Comment by Shubhamsaboo** [comment]
Hey! 

Sorry for the delayed reply. You have to make two changes on the following lines to use the fine-tuned model:

- [Line 23](https://github.com/Shubhamsaboo/kairos_gpt3/blob/master/GPT-3_Sandbox/email_generation/model_training_service.py#L23) change the engine name with the name of your fine-tuned model
- [Line 42](https://github.com/Shubhamsaboo/kairos_gpt3/blob/master/GPT-3_Sandbox/email_generation/model_training_service.py#L42) depending on your use case you can directly provide the input to the query function. So, it will ignore the training data!
